### ISSUE TITLE
Git commits are against Paul Miller

### ISSUE THREAD

**Issue by tombpain** [paulmillr/dotfiles#17]
Once installed my commits to stash now appear to be by 'Paul Miller'. Easily fixed but id call it an issue!
![screen shot 2015-06-09 at 18 40 40](https://cloud.githubusercontent.com/assets/1178271/8065096/1478a524-0ed7-11e5-8f1d-2c484db0507c.png)

**Comment by paulmillr** [comment]
¯\_(ツ)_/¯

**Comment by joaohkfaria** [comment]
Why did you close this issue? =.='

**Comment by paulmillr** [comment]
Adjust the configs by yourself when needed. I don't mind :joy_cat:

**Comment by joaohkfaria** [comment]
No warning and no backup of previously git config. Believe me, you can contribute and not be a dick at the same time :)
