### ISSUE TITLE
file="${file%.sh}"   file="${file%.sh}" 

### ISSUE THREAD

**Issue by askDing** [paulmillr/dotfiles#27]
Hi, paulmillr!
in this file located at  *etc/symlink-dotfiles.sh*, 
What does this statement do, `file="${file%.sh}"` in symlink-dotfiles.sh
It just rename file without suffix `.sh` then link files.

**Comment by paulmillr** [comment]
we are symlinking dotfiles/.zshrc.sh to $HOME/.zshrc without .sh extension
